package(default_visibility = ["//visibility:public"])

cc_library(
    name = "send_client",
    srcs = ["send_client.c"],
    hdrs = ["send_client.h"],
    deps = [
        "//core:send_core",
    ],
)

cc_library(
    name = "recv_client",
    srcs = ["recv_client.c"],
    hdrs = ["recv_client.h"],
    deps = [
        "//core:core",
    ],
)
